# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-22 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(error_messages={'unique': 'This email is already registered.'}, max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=35, null=True)),
                ('last_name', models.CharField(max_length=35, null=True)),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
            },
        ),
    ]
