# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-29 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugs_newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='last_name',
        ),
        migrations.AddField(
            model_name='subscription',
            name='name',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
